"""
Step 10 — export the qualified catalog in the shape db/dev/seed.py consumes.

Unions the current step 5 output (Tier 1: current night train stops) with the
step 6 manual additions and writes a CSV matching seed.py's
_ONTD_SEED_CSV_COLUMNS contract exactly. Keyed on OSM id, so a stop qualifying
both ways is written once and a step 5 re-run flows straight into the catalog
without touching the manual selection.

Which layer a stop came from is written alongside, to
stop_seed_provenance.csv: the catalog itself has to match seed.py's column
contract exactly, so the provenance can't ride in it. Without that sidecar
nothing on disk distinguishes a stop a night train serves today from one added
by hand.

country
    Taken from the ONTD export via the step 4 join where one exists, since ONTD
    is curated national data; otherwise the source layer's own value. Steps 5
    and 6 already apply the same preference, so this is a safety net rather
    than the place the correction happens — step 6 reports what it changed.

stop_timezone
    Derived from the country as an IANA name. The legacy step 6 file carried a
    bare UTC offset instead, which cannot express DST and was wrong for Ireland
    (marked +1); the schema and the rest of the catalog use IANA names.

The catalog is a single file carrying everything downstream needs: the
seven seed contract columns first (seed.py validates them as a header
prefix and ignores the rest until the schema migration), then a
human-readable provenance category, then the step 7 name/city/language
columns and the step 8 gauges. Step 7's enrichment is therefore a required
input; step 8's gauges are joined when present and warned about when not
(Overpass-dependent, resumable — the catalog should not block on it).

Two invariants guard the union against duplicate stations:
- no two catalog rows may share an ONTD id (same station through two OSM
  objects) — hard error;
- rows within 200 m of each other are reported for review (step 6's guards
  should have caught them; this is the belt to those braces).

stop_charge_eur comes from charges/data/station_charges.csv, generated by the
charge calibration notebooks in charges/, and is joined together with its
provenance: the VAT rate and the gross figure, what the charge is per, the
year it was published for, the country's own tariff class, and the source
document. A figure in a published catalog that cannot say where it came from
is not much better than no figure. A stop absent from that file is
written empty and seed.py inserts NULL, which resolves through the
country/global default (currently 11.28 EUR).
Empty is deliberate: a placeholder number would override that fallback and make
"which stops still need real charge data?" unanswerable, whereas NULL keeps the
question a one-line query.

Run from this directory:

    uv run python step10_export_seed_stops.py
"""

from __future__ import annotations

import csv
import math
from pathlib import Path

from data_sources import DATA_DIR, local_input

OUTPUT_PATH = DATA_DIR / "stop_seed_catalog.csv"
PROVENANCE_PATH = DATA_DIR / "stop_seed_provenance.csv"
ENRICHMENT_PATH = (
    DATA_DIR / "stop_seed_enrichment.csv"
)  # pre-2026-08 sidecar, removed if found

# The provenance column is UI-facing wording, derived from the qualification
# layer and the step 6 reason criterion. Editing a label here is enough — the
# detailed per-stop reasons stay in data/step6_manual_additions.csv and the
# step 6 notebook, which remain the record of the selection decisions.
PROVENANCE_LABELS = {
    "night_train_stop": "existing night train stop",
    "fua": "urban area currently without night train service",
    "tourism": "tourism region currently without night train service",
    "ferry": "ferry port currently without night train service",
    "border": "border / interchange station",
    "network": "network coherence addition",
}
PROVENANCE_FALLBACK = "manual addition"


def provenance_label(source: str, reason: str) -> str:
    if source == "step5":
        return PROVENANCE_LABELS["night_train_stop"]
    criterion = reason.partition(":")[0].split(" ")[0].strip()
    return PROVENANCE_LABELS.get(criterion, PROVENANCE_FALLBACK)


# Generated by charges/02_station_charges.ipynb, which reads the registered
# tariff documents. Gitignored like every other calibration artifact in the
# project — the notebooks are truth, this is their output.
CHARGES_PATH = (
    Path(__file__).resolve().parent / "charges" / "data" / "station_charges.csv"
)

# seed.py::_ONTD_SEED_CSV_COLUMNS — keep in lockstep.
SEED_COLUMNS = [
    "stop_id",
    "stop_name",
    "country_code",
    "stop_timezone",
    "stop_lat",
    "stop_lon",
    "stop_charge_eur",
]

# What the catalog keeps about a charge beyond the figure itself: the same
# provenance the tariff document carries, so "why does this stop cost that"
# is answerable from the published catalog and not only from the charge
# notebooks. Keyed by catalog column, valued by station_charges.csv column.
CHARGE_PROVENANCE_COLUMNS = {
    "stop_charge_vat_rate_per": "vat_rate_per",
    "stop_charge_incl_vat_eur": "stop_charge_incl_vat_eur",
    "stop_charge_basis": "basis",
    "stop_charge_price_basis_year": "price_basis_year",
    "stop_charge_class": "tariff_class",
    "stop_charge_source": "source_ref",
}

# One IANA zone per country. Derived from the country rather than a UTC offset
# so DST is handled by the zone database instead of being frozen into the data.
COUNTRY_TIMEZONES = {
    "AL": "Europe/Tirane",
    "AT": "Europe/Vienna",
    "BA": "Europe/Sarajevo",
    "BE": "Europe/Brussels",
    "BG": "Europe/Sofia",
    "BY": "Europe/Minsk",
    "CH": "Europe/Zurich",
    "CZ": "Europe/Prague",
    "DE": "Europe/Berlin",
    "DK": "Europe/Copenhagen",
    "EE": "Europe/Tallinn",
    "ES": "Europe/Madrid",
    "FI": "Europe/Helsinki",
    "FR": "Europe/Paris",
    "GB": "Europe/London",
    "GR": "Europe/Athens",
    "HR": "Europe/Zagreb",
    "HU": "Europe/Budapest",
    "IE": "Europe/Dublin",
    "IT": "Europe/Rome",
    "LT": "Europe/Vilnius",
    "LU": "Europe/Luxembourg",
    "LV": "Europe/Riga",
    "MD": "Europe/Chisinau",
    "ME": "Europe/Podgorica",
    "MK": "Europe/Skopje",
    "NL": "Europe/Amsterdam",
    "NO": "Europe/Oslo",
    "PL": "Europe/Warsaw",
    "PT": "Europe/Lisbon",
    "RO": "Europe/Bucharest",
    "RS": "Europe/Belgrade",
    "RU": "Europe/Moscow",
    "SE": "Europe/Stockholm",
    "SI": "Europe/Ljubljana",
    "SK": "Europe/Bratislava",
    "TR": "Europe/Istanbul",
    "UA": "Europe/Kyiv",
    "XK": "Europe/Belgrade",
}

# OSM ids whose step 4 match is junk — the OSM station is an unnamed or
# single-letter object hundreds of kilometres from the ONTD stop it was matched
# to. Excluded rather than seeded with a wrong location.
EXCLUDED_STOP_IDS = {
    "osm:n4896717721",  # ONTD Dağkadı Hızlı Tren İstasyonu -> OSM "tren", 2743 km
    "osm:n8515238217",  # ONTD Tekučica -> OSM "A", 355 km
    "osm:n310754741",  # ONTD Dej -> "Autogara Dej", the BUS station 2.6 km
    # out (fuzzy_raw). The real station, Dej Călători (osm:n2235196597),
    # is a step 6 addition instead.
    "osm:n2338638827",  # ONTD Lazarevac (RS) -> "Re", 938 km away on the
    # metre-gauge Centovalli line in Piedmont — a coords_mismatch fuzzy
    # match that step 5 flagged but did not block.
    # osm:n9553124517 ("Arad") was listed here after ONTD Közép-Garadna
    # junk-matched to it at 222 km — but the ban was by OSM id, and the id
    # is the REAL Arad station. Once step 5 matched the actual ONTD Arad
    # to it at <1 km, the ban blocked a legitimate stop (2026-08-29).
    # The lesson: exclude bad MATCHES upstream, not station ids here.
}


def load_station_charges() -> dict[str, dict]:
    """stop_id -> the charge row (figure plus its provenance), from the
    tracked station_charges.csv.

    Missing file is not an error: the catalog is then seeded entirely on the
    default, which is the honest state until real tariffs are collected.
    """
    if not CHARGES_PATH.is_file():
        print(
            f"  {CHARGES_PATH.name} not found — every stop_charge_eur left empty, "
            "so every stop resolves through the global default. Run "
            "charges/01_source_extraction.ipynb then 02_station_charges.ipynb "
            "to generate it."
        )
        return {}

    charges: dict[str, dict] = {}
    illustrative = 0
    with open(CHARGES_PATH, encoding="utf-8-sig", newline="") as fh:
        for line, row in enumerate(csv.DictReader(fh), start=2):
            stop_id = (row.get("stop_id") or "").strip()
            value = parse_float(row.get("stop_charge_eur"))
            if not stop_id or value is None:
                continue
            if value < 0:
                raise ValueError(f"{CHARGES_PATH.name} line {line}: negative charge")
            if stop_id in charges:
                raise ValueError(
                    f"{CHARGES_PATH.name} line {line}: duplicate {stop_id}"
                )
            charges[stop_id] = {"value": value, "row": row}
            # The charge notebooks register unsourced carry-over values under
            # this id; counted so a run says out loud how much is still
            # placeholder rather than measured.
            if (row.get("source_ref") or "").strip() == "ILLUSTRATIVE-CURATED":
                illustrative += 1

    print(f"  {len(charges)} station charges ({illustrative} still illustrative).")
    return charges


def parse_float(value):
    if value is None:
        return None
    text = str(value).strip().replace(",", ".")
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def load_step4_join() -> tuple[dict[str, str], dict[str, str]]:
    """OSM stop id -> (ONTD country code, ONTD id), from the step 4 join."""
    path = local_input("step4_MatchingONTDtoOSM.csv", "step4_MatchingONTDtoOSM.ipynb")
    countries, ontd_ids = {}, {}
    with open(path, encoding="utf-8-sig", newline="") as fh:
        for row in csv.DictReader(fh):
            osm_id = (row.get("osm_stop_id") or "").strip()
            if not osm_id:
                continue
            country = (row.get("ontd_country") or "").strip().upper()
            if country:
                countries.setdefault(osm_id, country)
            ontd_ids.setdefault(osm_id, (row.get("ontd_id") or "").strip())
    return countries, ontd_ids


def distance_km(lat1, lon1, lat2, lon2):
    """Equirectangular approximation — fine at the sub-kilometre scale the
    duplicate check works at."""
    mean_lat = math.radians((lat1 + lat2) / 2)
    dx = math.radians(lon2 - lon1) * math.cos(mean_lat)
    dy = math.radians(lat2 - lat1)
    return math.hypot(dx, dy) * 6371.0


def load_enrichment() -> tuple[list[str], dict[str, dict]]:
    """Step 7 columns plus step 8 gauges, keyed by stop id. Step 7 is a
    required pipeline stage now that its columns are part of the catalog;
    step 8 is Overpass-dependent and resumable, so its absence warns."""
    enrich_path = local_input("step7_enriched_stops.csv", "step7_enrich_stops.ipynb")
    with open(enrich_path, encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        # stop_id is the join key; stop_name is not appended as an extra
        # column but its value wins over the layer name below — step 7 owns
        # display naming (bilingual primaries, qualifier strips). country_code
        # is already a seed contract column, so step 7's copy is dropped too —
        # a duplicate header would break seed.py's exact-header validation.
        enrich_fields = [
            f
            for f in (reader.fieldnames or [])
            if f not in ("stop_id", "stop_name", "country_code")
        ]
        rows = {row["stop_id"]: row for row in reader}

    gauges_path = DATA_DIR / "step8_stop_gauges.csv"
    gauge_fields = ["gauges", "gauge_source"]
    if gauges_path.is_file():
        with open(gauges_path, encoding="utf-8-sig", newline="") as fh:
            for gauge_row in csv.DictReader(fh):
                row = rows.get(gauge_row["stop_id"])
                if row is not None:
                    row["gauges"] = gauge_row["gauges"]
                    row["gauge_source"] = gauge_row["gauge_source"]
    else:
        print(
            "  step8_stop_gauges.csv not found — run step8_stop_gauges.ipynb; "
            "sidecar carries no gauges."
        )

    return enrich_fields + gauge_fields, rows


def iter_candidates():
    """(source, stop_id, ontd_id, stop_name, source_country, lat, lon, reason)
    from step 5 then step 6. Step 5 first so its ONTD-backed row wins when a
    stop qualifies both ways."""
    step5_path = local_input(
        "step5_JoinedNTStops.csv", "step5_JoinNTStopsWithOSM.ipynb"
    )
    with open(step5_path, encoding="utf-8-sig", newline="") as fh:
        for row in csv.DictReader(fh):
            yield (
                "step5",
                (row.get("osm_stop_id") or "").strip(),
                (row.get("ontd_id") or "").strip(),
                (row.get("osm_stop_name") or row.get("ontd_name") or "").strip(),
                (row.get("ontd_country") or "").strip().upper(),
                parse_float(row.get("osm_lat")),
                parse_float(row.get("osm_lon")),
                f"night_train_stop:{(row.get('schedule_name') or '').strip()}",
            )
    step6_path = local_input(
        "step6_manual_additions.csv", "step6_manual_additions.ipynb"
    )
    with open(step6_path, encoding="utf-8-sig", newline="") as fh:
        for row in csv.DictReader(fh):
            yield (
                "step6_manual",
                (row.get("stop_id") or "").strip(),
                "",
                (row.get("stop_name") or "").strip(),
                (row.get("country") or "").strip().upper(),
                parse_float(row.get("stop_lat")),
                parse_float(row.get("stop_lon")),
                (row.get("reason") or "").strip(),
            )


def main() -> None:
    ontd_countries, ontd_ids_of = load_step4_join()
    charges = load_station_charges()
    enrich_fields, enrichment = load_enrichment()

    rows, unknown_tz = [], []
    stale_enrichment: list[tuple[str, str]] = []
    skipped: dict[str, str] = {}
    seen_ids = set()
    per_source = {"step5": 0, "step6_manual": 0}
    provenance = []

    for (
        source,
        stop_id,
        ontd_id,
        stop_name,
        source_country,
        lat,
        lon,
        reason,
    ) in iter_candidates():
        if not stop_id or stop_id in seen_ids:
            continue
        if stop_id in EXCLUDED_STOP_IDS:
            skipped.setdefault(stop_id, stop_name)
            continue
        seen_ids.add(stop_id)
        per_source[source] += 1

        ontd_id = ontd_id or ontd_ids_of.get(stop_id, "")
        country = ontd_countries.get(stop_id, source_country)

        timezone = COUNTRY_TIMEZONES.get(country)
        if timezone is None:
            # No country means no timezone, and a stop written without one would
            # be wrong rather than merely incomplete — collected and raised below
            # so it can never disappear from the catalog unnoticed.
            unknown_tz.append((stop_id, stop_name, country))
            continue

        if lat is None or lon is None:
            skipped[stop_id] = f"{stop_name} (missing coordinates)"
            continue

        enriched = enrichment.get(stop_id)
        if enriched is None:
            # Step 7 ran against older step 5/6 outputs — its columns for this
            # stop do not exist, and an all-empty row in the published catalog
            # would just be a quieter version of the same staleness.
            stale_enrichment.append((stop_id, stop_name))
            continue

        stop_name = enriched.get("stop_name") or stop_name
        provenance.append({"source": source, "reason": reason})
        row = {
            "_ontd_id": ontd_id,
            "_source": source,
            "stop_id": stop_id,
            "stop_name": stop_name,
            "country_code": country,
            "stop_timezone": timezone,
            "stop_lat": f"{lat:.7f}",
            "stop_lon": f"{lon:.7f}",
            "stop_charge_eur": (
                "" if stop_id not in charges else f"{charges[stop_id]['value']:.2f}"
            ),
            "provenance": provenance_label(source, reason),
        }
        # Charge provenance travels as columns beside the figure; empty for the
        # stops that resolve through the country or global default.
        charge_row = charges.get(stop_id, {}).get("row", {})
        row.update(
            {
                column: (charge_row.get(source_column) or "")
                for column, source_column in CHARGE_PROVENANCE_COLUMNS.items()
            }
        )
        row.update({field: enriched.get(field, "") for field in enrich_fields})
        rows.append(row)

    # --- invariant 1: one catalog row per ONTD station --------------------
    # Two OSM objects for the same station carry the same ONTD id through the
    # step 4 join; if both reach this point, step 6's guards were bypassed and
    # the catalog would seed the station twice. Hard error, not a warning.
    by_ontd: dict[str, list[dict]] = {}
    for row in rows:
        if row["_ontd_id"]:
            by_ontd.setdefault(row["_ontd_id"], []).append(row)
    ontd_dupes = {k: v for k, v in by_ontd.items() if len(v) > 1}
    if ontd_dupes:
        for ontd_id, twins in ontd_dupes.items():
            names = [(t["stop_name"], t["stop_id"], t["_source"]) for t in twins]
            print(f"  ONTD {ontd_id}: {names}")
        raise SystemExit(
            f"{len(ontd_dupes)} ONTD station(s) appear in the catalog through "
            "more than one OSM object — fix in step 6 (its duplicate guard "
            "should have caught this; if step 5 was re-run after step 6, "
            "re-run step 6)."
        )

    # --- invariant 2: report near-coincident rows -------------------------
    # 200 m apart is two objects for one station, not two stations. Reported
    # rather than raised: step 5 itself can legitimately contain distinct
    # stations closer than city blocks (Lille-Flandres / Lille-Europe sit at
    # ~450 m), so the reviewer decides, with the pair in front of them.
    NEAR_KM = 0.2
    located = [(row, float(row["stop_lat"]), float(row["stop_lon"])) for row in rows]
    located.sort(key=lambda item: item[1])
    near_pairs = []
    for i, (row_a, lat_a, lon_a) in enumerate(located):
        for row_b, lat_b, lon_b in located[i + 1 :]:
            if (lat_b - lat_a) * 111.32 > NEAR_KM:
                break
            if distance_km(lat_a, lon_a, lat_b, lon_b) <= NEAR_KM:
                near_pairs.append((row_a, row_b))
    if near_pairs:
        print(
            f"  WARNING: {len(near_pairs)} catalog pair(s) closer than {NEAR_KM * 1000:.0f} m:"
        )
        for row_a, row_b in near_pairs:
            print(
                f"    {row_a['stop_name']} ({row_a['stop_id']}, {row_a['_source']}) "
                f"~ {row_b['stop_name']} ({row_b['stop_id']}, {row_b['_source']})"
            )

    if stale_enrichment:
        raise SystemExit(
            f"{len(stale_enrichment)} catalog stop(s) missing from "
            f"step7_enriched_stops.csv — step 7 was run against older step 5/6 "
            f"outputs; re-run step7_enrich_stops.ipynb (and step 8): "
            f"{stale_enrichment[:5]}"
        )

    # Seed contract columns first (seed.py checks them as a header prefix),
    # provenance, then the enrichment block.
    fieldnames = (
        SEED_COLUMNS + list(CHARGE_PROVENANCE_COLUMNS) + ["provenance"] + enrich_fields
    )
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)

    # Former two-file layout — remove leftovers so there is exactly one
    # current answer to "which file seeds the stops".
    for stale in (ENRICHMENT_PATH, PROVENANCE_PATH):
        if stale.is_file():
            stale.unlink()
            print(f"  removed {stale.name} (folded into the catalog)")

    no_gauges = sum(1 for row in rows if not row.get("gauges"))
    if no_gauges:
        print(
            f"  {no_gauges} stop(s) without gauge data — run/resume "
            "step8_stop_gauges.ipynb and re-export if that number surprises you"
        )

    print(
        f"wrote {len(rows)} stops to {OUTPUT_PATH.name} "
        f"({per_source['step5']} from step 5, "
        f"{per_source['step6_manual']} manual step 6 additions)"
    )
    unexplained = sum(
        1 for p in provenance if p["source"] == "step6_manual" and not p["reason"]
    )
    if unexplained:
        print(
            f"  {unexplained} manual additions carry no reason "
            f"— see step6_manual_additions.ipynb"
        )
    if skipped:
        print(f"skipped {len(skipped)}: {skipped}")
    unknown_charges = sorted(set(charges) - seen_ids)
    if unknown_charges:
        print(
            f"  WARNING: {len(unknown_charges)} charge row(s) name a stop that is "
            f"not in the catalog — stale ids in {CHARGES_PATH.name}: "
            f"{unknown_charges[:5]}"
        )

    if unknown_tz:
        countries = sorted({country for _, _, country in unknown_tz if country})
        blank = [(i, n) for i, n, country in unknown_tz if not country]
        raise SystemExit(
            f"{len(unknown_tz)} stop(s) dropped for want of a timezone.\n"
            + (
                f"  no mapping for {countries} — add to COUNTRY_TIMEZONES\n"
                if countries
                else ""
            )
            + (
                f"  no country at all: {blank} — fix upstream in step 6\n"
                if blank
                else ""
            )
        )


if __name__ == "__main__":
    main()
