graphhopper:
  datareader.file: /app/data/europe-latest.osm.pbf
  graph.location: /app/graph-cache
  custom_models.directory: /app/custom_models

  profiles:
    - name: night_train
      turn_costs:
        vehicle_types: [train]
        u_turn_costs: 300
        enable_uturn_times: true
      custom_model_files: [rail.json, night_train.json, preferred_direction.json]

  profiles_ch:
    - profile: night_train

  profiles_lm:
    - profile: night_train
      maximum_lm_weight: 16

  graph.encoded_values: gauge,voltage,electrified,frequency,road_environment,max_speed,rail_access,rail_average_speed,railway_class,railway_service,preferred_direction
  graph.dataaccess.default_type: RAM_STORE
  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1
  routing.snap_preventions_default: tunnel, bridge, ferry
  routing.non_ch.max_waypoint_distance: 1000000
  import.osm.ignored_highways: footway,construction,cycleway,path,steps

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
      max_request_header_size: 50k
  request_log:
    appenders: []
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0
logging:
  level: INFO
  appenders:
    - type: console
      time_zone: UTC
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"