-- 2026-09-10_auto_stop_add_removed.sql
-- ---------------------------------------------------------------------
-- Assertion only — no schema change, no data change (WP18 phase B1).
--
-- ROUTE_BUILDER 0.9.34 removes auto_stop_addition mode 'add': the route
-- builder no longer adds stops of its own, and the API rejects 'add' with
-- a 400. Every stored proposal recomputes from its compute_request, so a
-- proposal whose request still says 'add' would fail on its next refresh
-- rather than quietly building a different route. This file makes that a
-- loud deploy failure instead, before the api container is allowed to
-- start.
--
-- Expected outcome: both checks silent, migration applies in
-- milliseconds. If the first RAISES, do NOT edit this file — fix the data
-- (see the message) and deploy again.
-- ---------------------------------------------------------------------

DO $$
DECLARE
    n_add       integer;
    n_missing   integer;
    n_auto_added integer;
BEGIN
    -- 1. HARD FAIL — a stored request the new route builder cannot honour.
    SELECT count(*) INTO n_add
    FROM proposals.proposals
    WHERE compute_request->>'auto_stop_addition' = 'add';

    -- 2. HARD FAIL — a request predating the resolved-request echo would
    --    take the API-boundary default, which was 'add' until 0.9.34 and
    --    is 'off' from here. Same silent route change, so same treatment.
    SELECT count(*) INTO n_missing
    FROM proposals.proposals
    WHERE compute_request->>'auto_stop_addition' IS NULL;

    IF n_add > 0 OR n_missing > 0 THEN
        RAISE EXCEPTION
            'auto_stop_addition ''add'' is no longer supported (ROUTE_BUILDER '
            '0.9.34): % proposal(s) request it explicitly, % carry no value '
            'and would have taken the old ''add'' default. Their next '
            'recompute would build a different route. Fix before deploying: '
            'freeze each one''s CURRENT stop list into its compute_request '
            'and set auto_stop_addition to ''off'' — the stops are in '
            'proposals.stop_times for that proposal''s current version. '
            'See docs/DEPLOY_HANDOVER.md section 14.',
            n_add, n_missing;
    END IF;

    -- 3. NOTICE — informational, never fatal. These proposals were built
    --    when 'add' existed and carry stops the builder chose. Nothing
    --    breaks now (their requests are clean, or step 1 would have
    --    fired), but the next refresh rebuilds them WITHOUT those stops,
    --    so their distance, cost and timetable will move.
    SELECT count(DISTINCT p.proposal_id) INTO n_auto_added
    FROM proposals.stop_times st
    JOIN proposals.proposals p
      ON st.trip_id LIKE 'P' || p.proposal_id || '_V' || p.proposal_version || '_%'
    WHERE st.auto_added;

    IF n_auto_added > 0 THEN
        RAISE NOTICE
            '% published proposal(s) carry auto-added stops. They will lose '
            'those stops on their next recompute — expect their KPIs to '
            'change. Nothing to do unless that surprises you.',
            n_auto_added;
    END IF;
END $$;
