# calibrated_coefficients.py
# ==========================
# Fitted coefficients of the night train energy model.
#
# REGENERATED by calib/02_energy_calibration.ipynb - DO NOT EDIT BY HAND.
# Provenance: full 02 run of 2026-08-30, 1192 fit rows.
#
# Mass basis: coach gross weight at 80% load, LOCOMOTIVE EXCLUDED
# (Composition.total_weight_t()); the locomotive resistance lives in the
# per-km constant B. Length basis: coach rake length, locomotive excluded.

from __future__ import annotations

PROVENANCE: str = "02-fit-2026-08-30"

# Highest realised average leg speed in the calibration sweep. Above it
# the v^2 term extrapolates on physics (exponent verified by
# exponent_check.py), not on data.
DRAG_IDENTIFIED_UP_TO_KMH: float = 179.4

# Start/stop energy per leg, per tonne. Without it, legs under 50 km
# under-predict by about a third.
A_PER_LEG_KWH_PER_T: float = 0

# Per-km constant, mass-independent: locomotive resistance and
# everything common to every composition.
B_PER_KM_KWH: float = 1.33044

# Rolling resistance per coach tonne-km.
C_PER_TKM_KWH: float = 0.00133564

# kWh/(t*km*(km/h)^2). Mass-linked share of drag.
K_MASS_DRAG: float = 4.30168e-07

# kWh/(m*km*(km/h)^2). Length-linked share of drag (skin friction),
# identified by the mass-matched composition pairs: +17% length at
# equal mass costs +6-8% drag.
K_LENGTH_DRAG: float = 8.71323e-07

# Locomotive auxiliary draw, measured against leg time (flat across
# all compositions in the calibration sample).
P_LOCO_AUX_KW: float = 99.9246

# ASSUMPTION, not measured: Trassenfinder was queried with coach hotel
# load off. Installed comfort power is 50-100 kVA per coach (UIC 550
# era; the UIC train-line cap is 50 kVA per coach); 15 kW is a mid
# estimate of the average draw, range 10-25 by season. Linear in time -
# changing it never requires re-collection.
P_HOTEL_PER_COACH_KW: float = 15.0
