"""
model.py
========
Version constant, description, changelog, and formula registry of the
Night Train Energy Model.

Bump ENERGY_CALC_VERSION when any change affects energy_kwh output:
  - Formula structure or regression coefficients change
  - New variables added to the energy model
  - Any change to calc_energy_consumption.py

ENERGY_FORMULAS documents the energy model for tool users: LaTeX,
plain-language descriptions, and input/output legends with units
(models/formula.py).

The model is calibrated against DB Trassenfinder technical runs; the
coefficients live in calibrated_coefficients.py, which
calib/02_energy_calibration.ipynb regenerates. Derivation, decisions log
and limitations: models/energy/calib/README.md.

TODO: GIT_SHA injected at build time by CI — see .github/workflows/backend-tests.yml
"""

from __future__ import annotations

from models.formula import Formula, FormulaParam

# =============================================================================
# VERSION
# =============================================================================

ENERGY_CALC_VERSION: str = "1.1.0"

GIT_SHA: str = "unknown"  # injected by CI

# =============================================================================
# STANDARD VALUES
# =============================================================================

# The flat 28 kWh/km placeholder (ENERGY_FLAT_FACTOR_KWH_KM) is retired:
# the calibration measured fleet-weighted intensity at 9.19 kWh/km, so the
# dummy overstated traction energy roughly threefold. Coefficients now live
# in calibrated_coefficients.py.

# Short, plain-language summary of what this model computes — embedded as-is
# in the "models" section of POST /api/proposal/calc's response, alongside
# ENERGY_CALC_VERSION and ENERGY_FORMULAS.
ENERGY_MODEL_DESCRIPTION: str = (
    "Traction energy model calibrated against Deutsche Bahn Trassenfinder "
    "technical runs: start/stop energy per leg, rolling resistance per "
    "tonne-kilometre, air resistance growing with train length and the "
    "square of average speed, plus a constant auxiliary and hotel-power "
    "draw for the running time. Coach hotel power is an assumption, not a "
    "measurement - Trassenfinder was queried with it switched off."
)

CHANGELOG: dict = {
    "1.1.0": {
        "date": "2026-08-30",
        "author": "david + claude",
        "changes": "Calibrated model replaces the flat 28 kWh/km dummy. "
        "E = A*m + d*(B + C*m) + d*(K_m*m + K_L*L)*v_avg^2 + "
        "(P_loco + P_hotel*n)*t. Fitted on 1,192 Trassenfinder samples "
        "(all 8 compositions) plus a 1,440-request booked-speed sweep over "
        "a mass/length factorial; drag identified to 165.5 km/h average "
        "and extrapolated on verified v^2 physics beyond. Locomotive "
        "auxiliaries measured at 99.9 kW; coach hotel power (15 kW/coach) "
        "is a documented assumption since Trassenfinder had coach load "
        "off. Mass basis is coaches-only (Composition.total_weight_t()); "
        "the train_weight formula was corrected accordingly. Coefficients "
        "committed in calibrated_coefficients.py, regenerated by "
        "calib/02_energy_calibration.ipynb. The per-composition "
        "energy_factor_* DB columns are DROPPED in the same commit - "
        "schema, seed, both loaders, the route serializer and the "
        "Composition/CompositionType fields (no migration; staging "
        "reseeds on deploy). docs/MODEL.md regenerates via "
        "scripts/generate_model_docs.py. EVERY energy_kwh output "
        "changes.",
    },
    "0.9.1": {
        "date": "2026-08-10",
        "author": "david",
        "changes": "version.py renamed to model.py (every model now anchors "
        "version, description, changelog, and formulas in a model.py). "
        "ENERGY_FORMULAS rebuilt on the shared Formula/FormulaParam "
        "dataclasses (models/formula.py): every formula carries a full "
        "input/output legend with units, descriptions rewritten in plain "
        "language for tool users. ADDITIVE response change once "
        "serialized: each models.energy.formulas entry gains 'inputs' and "
        "'output', and input params carry an optional 'ref' source "
        "pointer (models/formula.py). The flat placeholder factor moved "
        "into STANDARD VALUES as ENERGY_FLAT_FACTOR_KWH_KM (value "
        "unchanged, 28.0). Bjarne coordination batch. No computed number "
        "changes.",
    },
    "1.0.0": {
        "date": "2026-06-25",
        "author": "david",
        "changes": "Dummy implementation: flat 28.0 kWh/km factor. "
        "Does not account for weight, speed, or terrain. "
        "Requires calibration by energy model team — "
        "see models/energy/README.md and ONBOARDING.md.",
    },
}


# =============================================================================
# ENERGY FORMULA REGISTRY — LaTeX + plain-language description + input/output
# legend per formula (models/formula.py). Descriptions are written for tool
# users; developer detail lives in the comments next to each entry.
# =============================================================================

ENERGY_FORMULAS: dict[str, Formula] = {
    # ------------------------------------------------------------------
    # CALIBRATED MODEL (v1.1.0) — coefficients in
    # calibrated_coefficients.py, regenerated by calib/02.
    "energy_per_leg": Formula(
        latex=r"E_{kWh,l} = A \cdot m_t + d_{km,l} \left( B + C \cdot m_t "
        r"+ (K_m m_t + K_L L_m) \cdot \bar{v}^2_{kmh,l} \right) "
        r"+ (P_{loco} + P_{hotel} \cdot n_{coach}) \cdot t_{h,l}",
        description="Electricity used on one country leg: start/stop "
        "energy for the train's weight, rolling resistance over the "
        "distance, air resistance growing with train length and the "
        "square of average speed, and the on-board power supply "
        "(locomotive systems plus heating, air conditioning and light in "
        "the coaches) for as long as the leg takes.",
        inputs=(
            FormulaParam(
                symbol="m_t",
                ref="formula:energy.train_weight",
                description="Coach train weight at 80% load, locomotive excluded",
                unit="t",
            ),
            FormulaParam(
                symbol="L_m",
                description="Coach rake length, locomotive excluded",
                unit="m",
            ),
            FormulaParam(
                symbol="n_coach",
                description="Number of coaches",
                unit="1",
            ),
            FormulaParam(
                symbol="d_km,l",
                description="Distance of the country leg",
                unit="km",
            ),
            FormulaParam(
                symbol="v̄_kmh,l",
                ref="formula:energy.avg_speed",
                description="Average speed on the leg",
                unit="km/h",
            ),
            FormulaParam(
                symbol="t_h,l",
                description="Driving time on the leg, dynamics included",
                unit="h",
            ),
            FormulaParam(
                symbol="A, B, C, K_m, K_L, P_loco, P_hotel",
                description="Calibrated coefficients, fleet-wide. Fitted "
                "against DB Trassenfinder technical runs; the values live "
                "in models/energy/calibrated_coefficients.py and are "
                "regenerated by calib/02_energy_calibration.ipynb",
                unit="see models/energy/calibrated_coefficients.py",
            ),
        ),
        output=FormulaParam(
            symbol="E_kWh,l",
            description="Electricity used on the country leg",
            unit="kWh",
        ),
    ),
    "energy_per_km": Formula(
        latex=r"e_{kWh/km,l} = \frac{E_{kWh,l}}{d_{km,l}}",
        description="Energy use per kilometre on a country leg: total "
        "energy divided by distance. Used for display and for comparing "
        "countries.",
        inputs=(
            FormulaParam(
                symbol="E_kWh,l",
                ref="formula:energy.energy_per_leg",
                description="Electricity used on the country leg",
                unit="kWh",
            ),
            FormulaParam(
                symbol="d_km,l",
                description="Distance of the country leg",
                unit="km",
            ),
        ),
        output=FormulaParam(
            symbol="e_kWh/km,l",
            description="Energy use per kilometre",
            unit="kWh/km",
        ),
    ),
    "total_energy": Formula(
        latex=r"E_{total} = \sum_{seg} \sum_{l \in seg} E_{kWh,l}",
        description="Total electricity used on the trip: the energy of "
        "all country legs added up.",
        inputs=(
            FormulaParam(
                symbol="E_kWh,l",
                ref="formula:energy.energy_per_leg",
                description="Electricity used on each country leg",
                unit="kWh",
            ),
        ),
        output=FormulaParam(
            symbol="E_total",
            description="Total trip energy use",
            unit="kWh",
        ),
    ),
    # ------------------------------------------------------------------
    # INPUTS
    # ------------------------------------------------------------------
    "avg_speed": Formula(
        latex=r"\bar{v}_{kmh,l} = \frac{d_{km,l}}{t_{drive,h,l}}",
        description="Average speed per country leg: distance divided by "
        "driving time. Feeds the air resistance term of the energy "
        "model.",
        inputs=(
            FormulaParam(
                symbol="d_km,l",
                description="Distance of the country leg",
                unit="km",
            ),
            FormulaParam(
                symbol="t_drive,h,l",
                description="Driving time on the leg",
                unit="h",
            ),
        ),
        output=FormulaParam(
            symbol="v̄_kmh,l",
            description="Average speed on the leg",
            unit="km/h",
        ),
    ),
    "train_weight": Formula(
        latex=r"m_t = \sum_{coach} m_{coach,t}",
        description="Train weight as the energy model uses it: all coach "
        "gross weights at 80% load added up, WITHOUT the locomotive. The "
        "calibration data was collected on this basis (Trassenfinder's "
        "Wagenzugmasse excludes the traction unit), so the locomotive's "
        "own resistance is inside the per-km constant B rather than "
        "scaled by weight.",
        inputs=(
            FormulaParam(
                symbol="m_coach,t",
                ref="column:input_params.coach_types.coach_type_weight_gross_t",
                description="Weight of each coach",
                unit="t",
            ),
        ),
        output=FormulaParam(
            symbol="m_t",
            description="Coach train weight, locomotive excluded",
            unit="t",
        ),
    ),
}
